### ISSUE TITLE
是否有可能更详尽说明文档

### ISSUE THREAD

**Issue by yzqfjxm** [hexiaoyun128/gin-base-framework#2]
@hexiaoyun128 , 我从说明中看到不少有兴趣的技术点，我有一个项目也用到了GIN框架，其它的技术点是不很了解，但是感觉这会是一个很用的项目；恳请在有空时，进一步对于各个技术点和在项目中的使用能够多做一些说明讲解，将对其他人会有更多的帮助。我已编译运行了，感觉是一个纯api的项目，不知道对不对；最后感谢作者的分享。

**Comment by itcloudy** [comment]
确实是一个纯api的，前后端分离，前端不是我擅长的，暂时没推，同时后续会提供配合该框架的自动化接口测试框架和代码生成框架
